baseURL = 'https://mc-mineserver.de/'
languageCode = 'en-us'
title = 'McMineserver'
copyright = 'McMineserver'
timezone = 'Europe/Berlin'

disableKinds = ["RSS", "taxonomy", "term"]
disableHugoGeneratorInject = true
enableRobotsTXT = true

[sitemap]
  changeFreq = 'monthly'
  priority = 1

[minify]
  minifyOutput = true
  
  [minify.tdewolff.html]
    keepQuotes = true

[server]
  [[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "script-src 'self'; style-src 'self' https://fonts.googleapis.com 'sha256-1GeD51GjihuQuCjy5ksrpPdRZnsKlfZRgWOWtArRCl8='; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; default-src 'self'"
